set(_CATKIN_CURRENT_PACKAGE "my_legged_robots_description")
set(my_legged_robots_description_VERSION "0.0.0")
set(my_legged_robots_description_MAINTAINER "user <user@todo.todo>")
set(my_legged_robots_description_PACKAGE_FORMAT "1")
set(my_legged_robots_description_BUILD_DEPENDS "rospy")
set(my_legged_robots_description_BUILD_EXPORT_DEPENDS "rospy")
set(my_legged_robots_description_BUILDTOOL_DEPENDS "catkin")
set(my_legged_robots_description_BUILDTOOL_EXPORT_DEPENDS )
set(my_legged_robots_description_EXEC_DEPENDS "rospy")
set(my_legged_robots_description_RUN_DEPENDS "rospy")
set(my_legged_robots_description_TEST_DEPENDS )
set(my_legged_robots_description_DOC_DEPENDS )
set(my_legged_robots_description_URL_WEBSITE "")
set(my_legged_robots_description_URL_BUGTRACKER "")
set(my_legged_robots_description_URL_REPOSITORY "")
set(my_legged_robots_description_DEPRECATED "")