set(_CATKIN_CURRENT_PACKAGE "my_hopper_training")
set(my_hopper_training_VERSION "0.0.0")
set(my_hopper_training_MAINTAINER "user <user@todo.todo>")
set(my_hopper_training_PACKAGE_FORMAT "1")
set(my_hopper_training_BUILD_DEPENDS "rospy")
set(my_hopper_training_BUILD_EXPORT_DEPENDS "rospy")
set(my_hopper_training_BUILDTOOL_DEPENDS "catkin")
set(my_hopper_training_BUILDTOOL_EXPORT_DEPENDS )
set(my_hopper_training_EXEC_DEPENDS "rospy")
set(my_hopper_training_RUN_DEPENDS "rospy")
set(my_hopper_training_TEST_DEPENDS )
set(my_hopper_training_DOC_DEPENDS )
set(my_hopper_training_URL_WEBSITE "")
set(my_hopper_training_URL_BUGTRACKER "")
set(my_hopper_training_URL_REPOSITORY "")
set(my_hopper_training_DEPRECATED "")