set(_CATKIN_CURRENT_PACKAGE "my_legged_robots_sims")
set(my_legged_robots_sims_VERSION "0.0.0")
set(my_legged_robots_sims_MAINTAINER "user <user@todo.todo>")
set(my_legged_robots_sims_PACKAGE_FORMAT "1")
set(my_legged_robots_sims_BUILD_DEPENDS "rospy")
set(my_legged_robots_sims_BUILD_EXPORT_DEPENDS "rospy")
set(my_legged_robots_sims_BUILDTOOL_DEPENDS "catkin")
set(my_legged_robots_sims_BUILDTOOL_EXPORT_DEPENDS )
set(my_legged_robots_sims_EXEC_DEPENDS "rospy")
set(my_legged_robots_sims_RUN_DEPENDS "rospy")
set(my_legged_robots_sims_TEST_DEPENDS )
set(my_legged_robots_sims_DOC_DEPENDS )
set(my_legged_robots_sims_URL_WEBSITE "")
set(my_legged_robots_sims_URL_BUGTRACKER "")
set(my_legged_robots_sims_URL_REPOSITORY "")
set(my_legged_robots_sims_DEPRECATED "")